### ISSUE TITLE
Comparing files results in nullpointer in main

### ISSUE THREAD

**Issue by Siltyx** [valters/xsdiff#2]
java.lang.NullPointerException
	at io.github.valters.xsdiff.app.Main$App.run(Main.java:87)
	at io.github.valters.xsdiff.app.Main.main(Main.java:52)

When comparing OpenDrive 1.4 H Schema to OpenDrive 1.5 M schema. Download here http://www.opendrive.org/download.html.

**Comment by valters** [comment]
Are you somehow comparing it in root folder? The code seems to rely on having file.parent field not null. Not sure what's going on there - it's been years since I had to use this tool, to be honest.

**Comment by Siltyx** [comment]
No not comparing in root folder. Another funny thing is if you change the command to java -jar xsdiff-app-1.1.0.jar a/OpenDRIVE_1.4H.xsd b/OpenDRIVE_1.5M.xsd  the error changes. See error.txt
[error.txt](https://github.com/valters/xsdiff/files/3280871/error.txt)

**Comment by valters** [comment]
Ah, the XSD structure is just unexpected there. Something that code does not anticipate.

**Comment by Siltyx** [comment]
ok then this tool cant help me here, but thank you

**Comment by valters** [comment]
I corrected the issue regarding NPE, it was caused by incorrect handling of xsd:documentation node. @Siltyx  I did try to comparte OpenDrive 1.4 vs 1.5 schemas, but they are so much different, the diff report is not useful at all. They have dropped so many types and introduced so many new ones, the tool simply gets confused. It would need new approach to be able to handle changes on that level.
